#!/bin/sh

MYSELF=`which "$0" 2>/dev/null`
[ $? -gt 0 -a -f "$0" ] && MYSELF="./$0"

if [ "$#" -ne 2 ]; then
    echo "usage: "$(basename $MYSELF) "<jarfilename> <execname>"
    exit 1
fi

tail -9 $MYSELF | cat - $1 > $2
chmod +x $2
exit 0

############## DON'T TOUCH BELOW HERE!!! ###############ls
#!/bin/sh
MYSELF=`which "$0" 2>/dev/null`
[ $? -gt 0 -a -f "$0" ] && MYSELF="./$0"
java=java
if test -n "$JAVA_HOME"; then
    java="$JAVA_HOME/bin/java"
fi
exec "$java" $java_args -jar $MYSELF "$@"
exit 1
